### ISSUE TITLE
Does not work

### ISSUE THREAD

**Issue by ijaspley** [jnewland/airfoil-api#2]
module.js:457
    throw err;
    ^

Error: Cannot find module '../build/Release/dns_sd_bindings'
    at Function.Module._resolveFilename (module.js:455:15)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/siobhanlloyd/Downloads/airfoil-api-master/node_modules/mdns/lib/dns_sd.js:32:22)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)

npm ERR! Darwin 15.6.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "start"
npm ERR! node v6.7.0
npm ERR! npm  v3.10.3
npm ERR! code ELIFECYCLE
npm ERR! airfoil-api@0.0.1 start: `node app.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the airfoil-api@0.0.1 start script 'node app.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the airfoil-api package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node app.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs airfoil-api
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls airfoil-api
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
[npm-debug.log.txt](https://github.com/jnewland/airfoil-api/files/513633/npm-debug.log.txt)

**Comment by jnewland** [comment]
Hi @ijaspley! It looks like this is an error loading the `mdns` module. Their installation page has a few notes that may be helpful:

https://github.com/agnat/node_mdns#installation

Are you able to run the following without error?

```
$ node
> require('mdns')
>
```

Once you're able to do that, airfoil-api should start.

**Comment by ijaspley** [comment]
Error: Cannot find module '../build/Release/dns_sd_bindings'
    at Function.Module._resolveFilename (module.js:455:15)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/USER/Downloads/airfoil-api-master/node_modules/mdns/lib/dns_sd.js:32:22)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)

**Comment by ijaspley** [comment]
It seems I really don't know what I'm doing and I need someone to hold my hand :)
